
package LoginRegister;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import DataBase.My_Conx;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import MenuForm.Menu_Form;
import javax.swing.JOptionPane;

/**
 *
 * @author mizuru
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form Login_Form
     */
    public LoginForm() 
    {
        initComponents();
        
        // center the form
        this.setLocationRelativeTo(null);
        
        // create a black border for global panel
        Border global_Label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);        
        jPanel_Outer.setBorder(global_Label_border);
        
        // create a background for jLabel_Tittle
        Border tittle_border = BorderFactory.createMatteBorder(0, 0, 3, 0, Color.DARK_GRAY);
        jLabel_Tittle.setBorder(tittle_border);
        
        // create and set black border for jLabel_Minimize
        Border jLabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);        
        jLabel_Minimize.setBorder(jLabel_border);
        jLabel_Close.setBorder(jLabel_border);
        
        // create a border for the icons label to remove movement with the color of jPanel
        Border icon_border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153,153,255));        
        jLabel_Username.setBorder(icon_border);
        jLabel_Password.setBorder(icon_border);
        
        // create a border for username and password field
        Border Uname_Pass_border = BorderFactory.createMatteBorder(0,0,2,0, new Color(153,153,255));
        jTextField_Username.setBorder(Uname_Pass_border);
        jPasswordField_Password.setBorder(Uname_Pass_border);
        jLabel_Create_Account.setBorder(Uname_Pass_border);
        
        // create border for jLabel_Logo_Perpus
        Border Logo_Perpus_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Logo_Perpus.setBorder(Logo_Perpus_border);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Outer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_Password = new javax.swing.JLabel();
        jLabel_Username = new javax.swing.JLabel();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jTextField_Username = new javax.swing.JTextField();
        jButton_Login = new javax.swing.JButton();
        jLabel_Create_Account = new javax.swing.JLabel();
        jButton_Create_Account = new javax.swing.JButton();
        jLabel_Minimize = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_Tittle = new javax.swing.JLabel();
        jLabel_Logo_Perpus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_Outer.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jPanel3.setBackground(new java.awt.Color(170, 182, 251));

        jLabel_Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N

        jLabel_Username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username.png"))); // NOI18N

        jPasswordField_Password.setBackground(new java.awt.Color(170, 182, 251));
        jPasswordField_Password.setFont(new java.awt.Font("Hack", 0, 18)); // NOI18N
        jPasswordField_Password.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_Password.setText("password");
        jPasswordField_Password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPasswordField_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_PasswordFocusLost(evt);
            }
        });

        jTextField_Username.setBackground(new java.awt.Color(170, 182, 251));
        jTextField_Username.setFont(new java.awt.Font("Hack", 0, 18)); // NOI18N
        jTextField_Username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Username.setText("username");
        jTextField_Username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusLost(evt);
            }
        });
        jTextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsernameActionPerformed(evt);
            }
        });

        jButton_Login.setBackground(new java.awt.Color(51, 102, 255));
        jButton_Login.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        jButton_Login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Login.setText("Login");
        jButton_Login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_LoginMouseExited(evt);
            }
        });
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });

        jLabel_Create_Account.setText("Don't Have an Account?");

        jButton_Create_Account.setBackground(new java.awt.Color(51, 102, 255));
        jButton_Create_Account.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Create_Account.setText("Sign Up");
        jButton_Create_Account.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Create_Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Create_AccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_Create_AccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_Create_AccountMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Create_Account)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPasswordField_Password)
                        .addComponent(jTextField_Username, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                    .addComponent(jButton_Create_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Password))
                .addGap(18, 18, 18)
                .addComponent(jButton_Login)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Create_Account)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Create_Account)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel_Minimize.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        jLabel_Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Minimize.setText("-");
        jLabel_Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseExited(evt);
            }
        });

        jLabel_Close.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseExited(evt);
            }
        });

        jLabel_Tittle.setFont(new java.awt.Font("Suravaram", 0, 36)); // NOI18N
        jLabel_Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Tittle.setText("LOGIN PAGE");

        jLabel_Logo_Perpus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Logo_Perpus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoPerpus.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel_Logo_Perpus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Tittle)
                .addGap(74, 74, 74)
                .addComponent(jLabel_Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Minimize)
                        .addComponent(jLabel_Close))
                    .addComponent(jLabel_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Logo_Perpus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel_OuterLayout = new javax.swing.GroupLayout(jPanel_Outer);
        jPanel_Outer.setLayout(jPanel_OuterLayout);
        jPanel_OuterLayout.setHorizontalGroup(
            jPanel_OuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_OuterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_OuterLayout.setVerticalGroup(
            jPanel_OuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_OuterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Outer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Outer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseEntered
        
        Border jLabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red);
        jLabel_Minimize.setBorder(jLabel_border);
        jLabel_Minimize.setForeground(Color.red);
        
    }//GEN-LAST:event_jLabel_MinimizeMouseEntered

    private void jLabel_MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseExited
        
        Border jLabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Minimize.setBorder(jLabel_border);
        jLabel_Minimize.setForeground(Color.black);
        
    }//GEN-LAST:event_jLabel_MinimizeMouseExited

    private void jLabel_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseEntered
        
        Border jLabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red);
        jLabel_Close.setBorder(jLabel_border);
        jLabel_Close.setForeground(Color.red);
        
    }//GEN-LAST:event_jLabel_CloseMouseEntered

    private void jLabel_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseExited
        
        Border jLabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Close.setBorder(jLabel_border);
        jLabel_Close.setForeground(Color.black);
        
    }//GEN-LAST:event_jLabel_CloseMouseExited

    private void jTextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsernameActionPerformed
        
    }//GEN-LAST:event_jTextField_UsernameActionPerformed

    private void jTextField_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusGained
        
        // clear the textfield on focus if the text is "username"
        if(jTextField_Username.getText().trim().toLowerCase().equals("username"))
        {
            jTextField_Username.setText("");
            jTextField_Username.setForeground(Color.black);
        }
        
        // set a gray border for jLabel_Username
        Border jLabel_border_icon = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        jLabel_Username.setBorder(jLabel_border_icon);
        
    }//GEN-LAST:event_jTextField_UsernameFocusGained

    private void jTextField_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusLost
        
        // set textfield to username again if focus lost
        if(jTextField_Username.getText().trim().toLowerCase().equals("") 
           || jTextField_Username.getText().trim().toLowerCase().equals("username"))
        {
            jTextField_Username.setText("username");
            jTextField_Username.setForeground(new Color(153,153,153));
        }
        
        Border icon_border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153,153,255));        
        jLabel_Username.setBorder(icon_border);
        
    }//GEN-LAST:event_jTextField_UsernameFocusLost

    private void jPasswordField_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordFocusGained
        // convert password value to string
        String pass = String.valueOf(jPasswordField_Password.getPassword());
        // clear the textfield on focus if the text is "password"
        if(pass.trim().toLowerCase().equals("password"))
        {
            jPasswordField_Password.setText("");
            jPasswordField_Password.setForeground(Color.black);
        }
        //set border for border icon
        Border jLabel_border_icon = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        jLabel_Password.setBorder(jLabel_border_icon);
        
    }//GEN-LAST:event_jPasswordField_PasswordFocusGained

    private void jPasswordField_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordFocusLost
        
        String pass = String.valueOf(jPasswordField_Password.getPassword());
        // clear the textfield on focus if the text is "password"
        if(pass.trim().toLowerCase().equals("") || pass.trim().toLowerCase().equals("password"))
        {
            jPasswordField_Password.setText("password");
            jPasswordField_Password.setForeground(new Color(153,153,153));
        }
        
        Border icon_border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153,153,255));
        jLabel_Password.setBorder(icon_border);
    }//GEN-LAST:event_jPasswordField_PasswordFocusLost

    private void jButton_LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LoginMouseEntered
        
        // set jButton background
        jButton_Login.setBackground(new Color(255,153,153));
        jButton_Login.setForeground(Color.black);
        
    }//GEN-LAST:event_jButton_LoginMouseEntered

    private void jButton_LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LoginMouseExited
        
        // set jButton background
        jButton_Login.setBackground(new Color(51,102,255));
        jButton_Login.setForeground(Color.white);
    }//GEN-LAST:event_jButton_LoginMouseExited

    private void jLabel_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseClicked
        
        // to minimize when clicked
        this.setState(JFrame.ICONIFIED);
        
    }//GEN-LAST:event_jLabel_MinimizeMouseClicked

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        
        // to close program
        System.exit(0);
        
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
            
        PreparedStatement st;
        ResultSet rs;
        
        // get the username & password
        String username = jTextField_Username.getText();
        String password = String.valueOf(jPasswordField_Password.getPassword());
        
        // create a select query to check  if the username and the password exist in the database
        String query = "SELECT * FROM `users` WHERE `username` = ? AND `password` = ?";
        
        try {
            st = My_Conx.getConnection().prepareStatement(query);
            
            st.setString(1, username);
            st.setString(2, password);        
            rs = st.executeQuery();
            
            if(rs.next())
            {
                // show a new form
                Menu_Form form = new Menu_Form();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                //close the current form(login)
                this.dispose();
                
            }
            else
            {
                // error massage
                JOptionPane.showMessageDialog(null,"Invalid Username / Password", "Login Error", 2);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton_LoginActionPerformed

    private void jButton_Create_AccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Create_AccountMouseEntered
        
        jButton_Create_Account.setBackground(new Color(255,153,153));
        jButton_Create_Account.setForeground(Color.black);
        
    }//GEN-LAST:event_jButton_Create_AccountMouseEntered

    private void jButton_Create_AccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Create_AccountMouseExited
        
        jButton_Create_Account.setBackground(new Color(51,102,255));
        jButton_Create_Account.setForeground(Color.white);
        
    }//GEN-LAST:event_jButton_Create_AccountMouseExited

    private void jButton_Create_AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Create_AccountMouseClicked
        
        RegisterForm rg = new RegisterForm();
        rg.setVisible(true);
        rg.pack();
        rg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jButton_Create_AccountMouseClicked
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Create_Account;
    private javax.swing.JButton jButton_Login;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_Create_Account;
    private javax.swing.JLabel jLabel_Logo_Perpus;
    private javax.swing.JLabel jLabel_Minimize;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_Tittle;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Outer;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
