package MenuForm;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author mizuru
 */
public class Menu_Form extends javax.swing.JFrame {

    /**
     * Creates new form MenuForm
     */
    public Menu_Form() {
        initComponents();
        
        // Tempatkan munculnya selalu ditengah
        this.setLocationRelativeTo(null);
        
        // Border untuk jLabel_LogoINF_USK
        Border jLabel_Logo = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        jLabel_LogoINF_USK.setBorder(jLabel_Logo);
        
        // Border untuk jPanel_Dasar
        Border jPanel_Base = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jPanel_Dasar.setBorder(jPanel_Base);
        
        // Border untuk jLabel_Close jLabel_Minimize
        Border CloseMize_Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Close.setBorder(CloseMize_Border);
        jLabel_Minimize.setBorder(CloseMize_Border);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel_Dasar = new javax.swing.JPanel();
        jPanelFooter = new javax.swing.JPanel();
        kGradientPanel_Header = new keeptoo.KGradientPanel();
        jLabel_LogoINF_USK = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_Minimize = new javax.swing.JLabel();
        jLabel_Perpustakaan = new javax.swing.JLabel();
        jLabel_DatangLagi = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_Dasar.setBackground(new java.awt.Color(255, 255, 255));

        jPanelFooter.setBackground(new java.awt.Color(80, 92, 82));

        javax.swing.GroupLayout jPanelFooterLayout = new javax.swing.GroupLayout(jPanelFooter);
        jPanelFooter.setLayout(jPanelFooterLayout);
        jPanelFooterLayout.setHorizontalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelFooterLayout.setVerticalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        kGradientPanel_Header.setkEndColor(new java.awt.Color(106, 145, 113));
        kGradientPanel_Header.setkGradientFocus(50);
        kGradientPanel_Header.setkStartColor(new java.awt.Color(62, 207, 88));

        jLabel_LogoINF_USK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoInformatikaUSK.png"))); // NOI18N

        jLabel_Close.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseExited(evt);
            }
        });

        jLabel_Minimize.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        jLabel_Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Minimize.setText("-");
        jLabel_Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseExited(evt);
            }
        });

        jLabel_Perpustakaan.setFont(new java.awt.Font("Noto Serif", 1, 22)); // NOI18N
        jLabel_Perpustakaan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Perpustakaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Perpustakaan.setText("PERPUSTAKAN");

        jLabel_DatangLagi.setFont(new java.awt.Font("Noto Serif", 1, 20)); // NOI18N
        jLabel_DatangLagi.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_DatangLagi.setText("DATANG LAGI");

        javax.swing.GroupLayout kGradientPanel_HeaderLayout = new javax.swing.GroupLayout(kGradientPanel_Header);
        kGradientPanel_Header.setLayout(kGradientPanel_HeaderLayout);
        kGradientPanel_HeaderLayout.setHorizontalGroup(
            kGradientPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(jLabel_LogoINF_USK, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(kGradientPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel_HeaderLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel_Perpustakaan, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                        .addComponent(jLabel_Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(kGradientPanel_HeaderLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel_DatangLagi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        kGradientPanel_HeaderLayout.setVerticalGroup(
            kGradientPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_LogoINF_USK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kGradientPanel_HeaderLayout.createSequentialGroup()
                        .addGroup(kGradientPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel_HeaderLayout.createSequentialGroup()
                                .addGroup(kGradientPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_Minimize)
                                    .addComponent(jLabel_Close))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel_HeaderLayout.createSequentialGroup()
                                .addComponent(jLabel_Perpustakaan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel_DatangLagi)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_DasarLayout = new javax.swing.GroupLayout(jPanel_Dasar);
        jPanel_Dasar.setLayout(jPanel_DasarLayout);
        jPanel_DasarLayout.setHorizontalGroup(
            jPanel_DasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kGradientPanel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_DasarLayout.setVerticalGroup(
            jPanel_DasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DasarLayout.createSequentialGroup()
                .addComponent(kGradientPanel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                .addComponent(jPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Dasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Dasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked

        // to close program
        System.exit(0);

    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jLabel_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseEntered

        Border jLabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red);
        jLabel_Close.setBorder(jLabel_border);
        jLabel_Close.setForeground(Color.red);

    }//GEN-LAST:event_jLabel_CloseMouseEntered

    private void jLabel_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseExited

        Border jLabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Close.setBorder(jLabel_border);
        jLabel_Close.setForeground(Color.black);

    }//GEN-LAST:event_jLabel_CloseMouseExited

    private void jLabel_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseClicked

        // to minimize when clicked
        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabel_MinimizeMouseClicked

    private void jLabel_MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseEntered

        Border jLabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red);
        jLabel_Minimize.setBorder(jLabel_border);
        jLabel_Minimize.setForeground(Color.red);

    }//GEN-LAST:event_jLabel_MinimizeMouseEntered

    private void jLabel_MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseExited

        Border jLabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Minimize.setBorder(jLabel_border);
        jLabel_Minimize.setForeground(Color.black);

    }//GEN-LAST:event_jLabel_MinimizeMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_DatangLagi;
    private javax.swing.JLabel jLabel_LogoINF_USK;
    private javax.swing.JLabel jLabel_Minimize;
    private javax.swing.JLabel jLabel_Perpustakaan;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanel_Dasar;
    private keeptoo.KGradientPanel kGradientPanel_Header;
    // End of variables declaration//GEN-END:variables
}
